version: '3'
services:
  mqtt-panel-webserver:
    image: icclab/mqtt-panel-webserver
    build:
      context: ./build-container
      dockerfile: Dockerfile.mqtt-panel-webserver
    ports:
     - "${MQTT_PANEL_PORT}:8080"
    environment:
     - MQTT_SERVER=${MQTT_SERVER}
     - MQTT_PORT=${MQTT_PORT}
