site_name: SmartSDK Recipes
site_description: Docker recipes for FIWARE Generic Enablers
docs_dir: 'recipes'
pages:
  - Home: index.md
  - 'Recipes':
    - 'Data/Context Management':
        - 'Context Broker':
          - 'Intro': 'data-management/context-broker/readme.md'
          - 'Simple': 'data-management/context-broker/simple/readme.md'
          - 'HA': 'data-management/context-broker/ha/readme.md'
        - 'STH':
          - 'Intro': 'data-management/sth/readme.md'
          - 'Standalone': 'data-management/sth/standalone/readme.md'
          - 'HA': 'data-management/sth/ha/readme.md'
    - 'IoT Services Enablement':
        - 'IoT Broker': 'iot-services/readme.md'
    - 'Utils':
        - 'Mongodb':
          - 'Replica Set': 'utils/mongodb/replica/readme.md'
  - 'Tools': 'tools/readme.md'
theme: readthedocs
markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
repo_url: https://github.com/smartsdk/smartsdk-recipes
edit_uri: edit/master/recipes/
