version: '3.3'

services:

  iotagent:
    image: fiware/iotagent-ul:${IOTA_VERSION:-1.5.0}
    entrypoint: "bin/iotagent-ul config.js"
    ports:
      # Agent HTTP transport port (Southbound)
      - "${IOTA_HTTP_PORT:-7896}:${IOTA_HTTP_PORT:-7896}"
      # Agent Northbound port
      - "${IOTA_NORTH_PORT:-4041}:${IOTA_NORTH_PORT:-4041}"
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
    configs:
      - source: iota-ul-conf
        target: /opt/iotaul/config.js
    networks:
      - backend

configs:
  iota-ul-conf:
    file: ./config.js
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_MTU:-1400}

  backend:
    external: true
