version: '3.3'

services:
  viz:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "8282:8080"
    networks:
      - backend
      - frontend

networks:
  backend:
    external: true
  frontend:
    external: true
