version: '3'

services:

    orion:
        image: fiware/orion:${ORION_VERSION}
        ports:
            - "1026:1026"
        command: -logLevel DEBUG -dbhost ${MONGO_SERVICE_URI} -rplSet ${REPLICASET_NAME} -dbTimeout 10000
        deploy:
            replicas: 1
        networks:
            - backend
            - frontend
        healthcheck:
          test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
          interval: 1m
          timeout: 10s
          retries: 3

networks:
    default:
        driver_opts:
            com.docker.network.driver.mtu: ${DOCKER_MTU:-1400}
    backend:
        driver: overlay
        external: true
    frontend:
        driver: overlay
        external: true
