version: '3'

services:
    mongo:
      image: mongo:3.2
      command: --nojournal
      networks:
        - orion
    orion:
      image: fiware/orion:1.9.0
      ports:
        - 1026:1026
      command: -dbhost mongo
      networks:
        - orion

networks:
  orion:
    driver: overlay
