version: '3.3'

services:

  orion:
    image: fiware/orion:${ORION_VERSION:-1.7.0}
    ports:
      - "1026:1026"
    command: -logLevel DEBUG -dbhost mongo -dbTimeout 10000
    networks:
      - backend

  mongo:
    image: mongo:${MONGO_VERSION:-3.2}
    entrypoint: [ "/usr/bin/mongod", "--journal", "--smallfiles"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 1m30s
    networks:
      - backend
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:

networks:
  # to make sure it works even with docker-compose up.
  default:
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_MTU:-1400}

  backend:
    external: true
