version: '3'

services:

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    networks:
      - backend

networks:
    default:
        driver_opts:
            com.docker.network.driver.mtu: 1400
    backend:
        driver: overlay
        external: true
