version: '3.3'
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    deploy:
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
    networks:
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    external: true
  frontend:
    external: true
